### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by motikolorado** [FangLee2003/decentralized-social-network#1]
Please explain how to install the dependencies and start a live preview in vs code. I tried yarn, yarn start but i got errors. please just explain the commands needed to start this project and what to change in the files.

**Comment by motikolorado** [comment]
@FangLee2003 You can add it in the readme so everyone can see.

**Comment by FangLee2003** [comment]
> @FangLee2003 You can add it in the readme so everyone can see.

Hi @motikolorado,

This project is still in beta so there are a lot of bugs. You can follow me to receive notifications when I finish it and write the manual in the Readme. Until then, you can search how to set up a project with nextjs, tailwind css, phantom wallet, rust, anchor, solana, netlify, ...

I apologize for this inconvenience.

**Comment by motikolorado** [comment]
I think I'll just wait for you to finish it... its a great work you're doing here
